In [65]:
import csv
import numpy as np
from os import listdir
import copy

In [70]:
def analyse_file(path):
    with open(path, "rb") as f:
        reader = csv.reader(f)
        dictTemplate= {"proposed":[],"autoexe":[], "doit":[], "cancel":[], "skip":[], "select":[], "remove":[], "press":[]}
        dicts=[copy.deepcopy(dictTemplate),copy.deepcopy(dictTemplate),copy.deepcopy(dictTemplate),copy.deepcopy(dictTemplate)]
        tStart=0
        roundNumber = 0
        for r in reader:
            if r[1] == "start":
                tStart=int(r[0])
            elif r[1] == "endround":
                roundNumber+=1
            else:
                if roundNumber < 4:
                    dicts[roundNumber][r[1]].append((int(r[0])-tStart)/1000.)
    return dicts
        

In [71]:
path = "../supervisor/condition-sparc-normal"
#filenames = listdir(path)
#filenames.sort()
#for i,f in enumerate(filenames):
#    d = analyse_file(path+"/"+f)
d=analyse_file(path+"/2018-01-19T14:18:40.csv")

In [72]:
d[0]

{'autoexe': [23.857, 28.296, 35.433, 43.482, 64.892, 77.901, 82.768, 87.183],
 'cancel': [7.379, 78.204, 83.155],
 'doit': [],
 'press': [19.189, 31.127, 38.259, 46.183, 70.675, 91.172],
 'proposed': [5.507,
  17.994,
  21.848,
  26.245,
  30.542,
  33.356,
  37.773,
  41.469,
  45.858,
  48.631,
  62.788,
  69.368,
  69.873,
  75.898,
  80.765,
  85.181,
  85.749,
  89.623],
 'remove': [],
 'select': [2.183,
  10.664,
  19.189,
  31.127,
  39.123,
  46.183,
  58.729,
  67.544,
  70.677,
  74.509,
  91.173],
 'skip': [50.695]}

In [19]:
bad

array([[  3.,   3.,   2.],
       [ 14.,   7.,   6.],
       [  5.,  11.,  11.],
       [  7.,   2.,   4.],
       [  0.,   3.,   2.],
       [  0.,   1.,   2.],
       [  1.,   1.,   2.],
       [  9.,   0.,   0.]])

In [27]:
times_q

array([ 14961.,   5484.,  36668.])

In [28]:
times_r

array([ 32421.,  20382.,  20788.,  16079.])

In [29]:
points

array([ 572.80425  ,  519.56625  ,  509.3403125,  505.480625 ])

In [31]:
age

'12'

In [23]:
gender

'female'

In [32]:
names = listdir("../analyse")

In [33]:
names.sort()

In [34]:
names

['2017-12-05T15:23:06 M.csv',
 '2017-12-15T16:46:14.bag',
 '2017-12-15T16:46:14.csv',
 '2017-12-19T13:29:11.bag',
 '2017-12-19T13:29:11.csv',
 '2017-12-19T13:48:45.bag',
 '2017-12-19T13:48:45.csv',
 '2017-12-20T15:53:18.csv',
 '2017-12-20T16:13:36.csv',
 '2017-12-20T17:32:19.bag',
 '2018-01-10T15:27:40.csv',
 '2018-01-10T16:46:31.csv',
 '2018-01-10T16:52:26.csv']

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])